import pyttsx3

engine = pyttsx3.init()
engine.setProperty("rate", 170)   # speaking speed
engine.setProperty("volume", 1.0) # volume 0.0–1.0

SCENES = [
    {"id": 1, "filename": "scene_01_intro.wav",
     "text": "Alright. Welcome to BADGRTechnologies L L C."},
    {"id": 2, "filename": "scene_02_today_problem.wav",
     "text": "Today, we're gonna cut right through all the hype around A I, and fact check a solution for a huge problem that every small service business runs into."},
    {"id": 3, "filename": "scene_03_phone_5pm.wav",
     "text": "You know the one. The phone stops ringing at 5 P M, but your customers, they don't stop calling."},
    {"id": 4, "filename": "scene_04_advantage_data.wav",
     "text": "We're gonna break down how some new tech can actually turn this leak into a huge advantage, and we're using carefully verified twenty twenty four, twenty twenty five industry data to do it."},
    {"id": 5, "filename": "scene_05_picture_this.wav",
     "text": "So picture this. You've had a long day. You're finally home, and the business phone starts buzzing."},
    {"id": 6, "filename": "scene_06_customer_emergency.wav",
     "text": "Now for your potential customer, their emergency is just getting started. Maybe a pipe just burst."},
    {"id": 7, "filename": "scene_07_turning_point_call.wav",
     "text": "That one moment, that single phone call, is a massive turning point for your business."},
    {"id": 8, "filename": "scene_08_what_happens_call.wav",
     "text": "So what really happens to that call?"},
    {"id": 9, "filename": "scene_09_benchmarks_intro.wav",
     "text": "You know, it's fascinating when you look at the documented benchmarks. Forget what you think happens."},
    {"id": 10, "filename": "scene_10_38_percent.wav",
     "text": "The hard data shows that only about thirty eight percent of calls actually get answered by a live person."},
    {"id": 11, "filename": "scene_11_voicemail_no_response.wav",
     "text": "The rest? Well, they're split pretty evenly between going straight to a voicemail box, and just getting no response at all."},
    {"id": 12, "filename": "scene_12_two_thirds_lost.wav",
     "text": "Think about that. Nearly two thirds of your potential customers just hang up without ever talking to anyone."},
    {"id": 13, "filename": "scene_13_9pm_not_option.wav",
     "text": "And in a real emergency, like that 9 P M pipe burst we talked about, waiting is just not an option."},
    {"id": 14, "filename": "scene_14_seventy_eight_percent.wav",
     "text": "Industry analyses have found that a pretty staggering seventy eight percent of people who don't get an answer right away, they don't even bother leaving a message. Nope, they just hang up and call the next name on Google."},
    {"id": 15, "filename": "scene_15_not_just_missed.wav",
     "text": "That's not just a missed call. You've literally just handed a job, and a customer, directly to your competition."},
    {"id": 16, "filename": "scene_16_what_cost.wav",
     "text": "So what does that actually cost you?"},
    {"id": 17, "filename": "scene_17_slide_math.wav",
     "text": "Well, this slide puts a number on it. Let's do some quick real world math."},
    {"id": 18, "filename": "scene_18_500_calls_setup.wav",
     "text": "Based on industry averages, if you miss around five hundred calls a month, and let's say the average job is worth two hundred dollars, and you close about fifteen percent of your leads,"},
    {"id": 19, "filename": "scene_19_180k_loss.wav",
     "text": "you're looking at a potential revenue loss of one hundred eighty thousand dollars a year. That is a massive leak from what seems like a pretty small hole."},
    {"id": 20, "filename": "scene_20_solution_shift.wav",
     "text": "Okay, so let's get into the solution. How do you plug that leak?"},
    {"id": 21, "filename": "scene_21_not_generic_call_center.wav",
     "text": "We're not talking about some generic overseas call center. We're talking about something way smarter, way faster, and most importantly, something you actually own."},
    {"id": 22, "filename": "scene_22_local_ai_front_desk.wav",
     "text": "A local, on site, customized to your company's needs BADGRTech A I Agent assistant, that basically becomes your twenty four seven front desk."},
    {"id": 23, "filename": "scene_23_define_local_ai.wav",
     "text": "And to be really clear about what we mean, a local A I voice assistant is a system that runs on a small server that's physically in your office."},
    {"id": 24, "filename": "scene_24_what_it_does.wav",
     "text": "It answers your calls, it handles all the basic questions, it can even book jobs around the clock."},
    {"id": 25, "filename": "scene_25_key_data_stays.wav",
     "text": "But the key part is that it keeps all of your customer data on hardware that you own, and you control."},
    {"id": 26, "filename": "scene_26_cloud_vs_local.wav",
     "text": "So this is the really crucial difference. With a standard cloud A I, your customer conversations are being processed on somebody else's computer. With a local A I, that data, which is your most valuable asset in the long run, stays with you."},
    {"id": 27, "filename": "scene_27_beyond_privacy.wav",
     "text": "This isn't just a privacy thing. It's about building a real asset that belongs completely to your business."},
    {"id": 28, "filename": "scene_28_make_real_composite.wav",
     "text": "Okay, let's make this real. Let's see how this actually works. To do that, we're going to walk through what we call a composite case study. We'll call our example company Reliable Repairs."},
    {"id": 29, "filename": "scene_29_model_transparency.wav",
     "text": "And this whole scenario is built from verified, fact checked results from all across the service industry. Reliable Repairs isn't a real single company. It's a model, built from real numbers."},
    {"id": 30, "filename": "scene_30_four_week_intro.wav",
     "text": "Now, you might think rolling this out would be a huge headache, but it can be surprisingly quick. A four week plan is a really realistic pattern."},
    {"id": 31, "filename": "scene_31_week_one.wav",
     "text": "Week one is all about strategy. You map out your leaks, and you set up that little local server."},
    {"id": 32, "filename": "scene_32_week_two.wav",
     "text": "Week two is training. You feed the A I your company's F A Qs, your service info, maybe even recordings of your best phone calls, so it learns to talk like you do."},
    {"id": 33, "filename": "scene_33_week_three_shadow.wav",
     "text": "Week three is super important. It's called shadow mode. The A I just listens in and suggests answers internally, so you can fine tune it."},
    {"id": 34, "filename": "scene_34_week_four_live.wav",
     "text": "And then week four, you go live, starting with just after hours and weekend calls."},
    {"id": 35, "filename": "scene_35_results_intro.wav",
     "text": "So after all that, what kind of results can a business like Reliable Repairs actually expect? Let's look at the hard numbers from real world examples, based on what the current industry benchmarks are showing us."},
    {"id": 36, "filename": "scene_36_speed_intro.wav",
     "text": "First up, speed. And speed is everything. Validated deployments have documented a reduction in customer response time of over eighty percent."},
    {"id": 37, "filename": "scene_37_caller_change.wav",
     "text": "For that caller at night, the change is even bigger. It goes from, we'll call you back tomorrow morning, to instant intake. The problem is being handled right now."},
    {"id": 38, "filename": "scene_38_efficiency.wav",
     "text": "Next, let's talk about efficiency. Case studies are showing that a well trained A I assistant can handle the vast majority of routine calls. We're talking seventy, even eighty percent of those common questions about services, hours, or availability."},
    {"id": 39, "filename": "scene_39_freeing_humans.wav",
     "text": "And what does that do? It frees up your actual human staff to focus on the complicated jobs and the high value customer relationships that really make your business grow."},
    {"id": 40, "filename": "scene_40_bottom_line_intro.wav",
     "text": "And finally, of course, the bottom line."},
    {"id": 41, "filename": "scene_41_25_percent_uplift.wav",
     "text": "Research consistently shows that when you can respond to leads in just a few minutes instead of a few hours, you see huge gains. An uplift of around twenty five percent in sales productivity is a pretty common benchmark."},
    {"id": 42, "filename": "scene_42_direct_growth.wav",
     "text": "Just by capturing those after hours calls you were losing before, you are directly fueling new growth."},
    {"id": 43, "filename": "scene_43_table_summary.wav",
     "text": "So, this table really just sums up the whole transformation perfectly. Look at the difference."},
    {"id": 44, "filename": "scene_44_before_after.wav",
     "text": "You go from a next day response to an instant one. You go from having only your staff handle calls, to a hybrid model with both A I and staff. You stop leaking revenue, and you start actually capturing it, growing it by around twenty five percent."},
    {"id": 45, "filename": "scene_45_data_ownership.wav",
     "text": "And maybe the biggest one of all, you take one hundred percent ownership of your customer data. It's a total shift in how your business runs."},
    {"id": 46, "filename": "scene_46_back_to_start.wav",
     "text": "So this all brings us right back to where we started, but now it's framed as a really clear business decision."},
    {"id": 47, "filename": "scene_47_competition_survival.wav",
     "text": "This isn't just about being convenient anymore. It's about competition. It's about survival."},
    {"id": 48, "filename": "scene_48_question_itself.wav",
     "text": "In a world where customers just hire the first person who actually answers the phone, the question kind of asks itself."},
    {"id": 49, "filename": "scene_49_9pm_question.wav",
     "text": "If your competitor can answer that 9 P M call instantly, with an A I that sounds just like their best employee, can you really afford to let your phone go dark after hours?"}
]

for scene in SCENES:
    print(f"Rendering scene {scene['id']}: {scene['filename']}")
    engine.save_to_file(scene["text"], scene["filename"])
    engine.runAndWait()
